# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4cca96cf6f423deb6897642b471a5737e1fd340afa020c7d590411e4ac58d7b7cef409425088c7a31309320f8b7b2c6f490511243dc1ba43feeaa99eb0c9b5c

test:
  secret_key_base: dfe84ad7f807d7c3c7045470c554460b5d5e07263b9aeb691ebc63f9c4ada02c70d791452b7d1b8ba8a9629c17441e0d8357e3579f4e8f0ab715afd6558d2f58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
